[project]
name = 'Rare-Disease-Research-Collaboration'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.decentralized-peer-review]
path = 'contracts/decentralized-peer-review.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-breakthrough-nft]
path = 'contracts/research-breakthrough-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-grant-management]
path = 'contracts/research-grant-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
